import { ClaimEpisode, User } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    name: 'Dr. Raditya Pratama, M.H.Kes',
    email: 'analyst@bpjs-kesehatan.go.id',
    role: 'analyst',
    organization: 'Divisi Manajemen Klaim & Utilisasi JKN',
  },
  {
    id: 2,
    name: 'Siti Nurhaliza, S.Si, M.Stat',
    email: 'policy@bpjs-kesehatan.go.id',
    role: 'policy_officer',
    organization: 'Deputi Bidang Kebijakan Jaminan Kesehatan',
  },
  {
    id: 3,
    name: 'Administrator TI PREVIA',
    email: 'admin@previa.jkn.go.id',
    role: 'admin',
    organization: 'Pusat Data dan Informasi BPJS Kesehatan',
  },
];

export const INITIAL_EPISODES: ClaimEpisode[] = [
  {
    id: 1024,
    episode_code: 'JKN-2026-084291',
    patient_pseudonym: 'Peserta Anonymized #84291 (Pria, 58 th)',
    provider_id: 'PRV-DIY-001',
    provider_name: 'RSUP Dr. Sardjito',
    provider_type: 'rsup',
    province_code: '34',
    province_name: 'D.I. Yogyakarta',
    episode_type: 'rawat_inap',
    diagnosis_code: 'I20.0',
    diagnosis_group: 'Kardiovaskular',
    diagnosis_description: 'Sindrom Koroner Akut (Unstable Angina Pectoris)',
    length_of_stay: 7,
    service_utilization_count: 12,
    claim_cost: 8420000, // Rp 8.420.000 matching PRD killer case!
    risk_score: 82,
    risk_level: 'critical',
    readmission_risk: 34,
    episode_started_at: '2026-02-14',
    episode_ended_at: '2026-02-21',
    related_episodes_count: 3,
    notes: 'Pasien rujukan berjenjang dengan riwayat hipertensi stage 2 dan dislipidemia. Mengalami perpanjangan rawat inap paska stabilisasi.',
    services: [
      {
        id: 'srv-1',
        service_code: 'AKOM-ICU',
        service_name: 'Akomodasi Ruang Rawat Inap & ICU Jantung (7 Hari)',
        service_category: 'akomodasi',
        service_date: '2026-02-14',
        quantity: 7,
        unit: 'hari',
        cost: 3150000,
      },
      {
        id: 'srv-2',
        service_code: 'MED-CATH',
        service_name: 'Prosedur Kateterisasi Diagnostik & Monitor Hemodinamik',
        service_category: 'tindakan_medis',
        service_date: '2026-02-15',
        quantity: 1,
        unit: 'tindakan',
        cost: 2450000,
      },
      {
        id: 'srv-3',
        service_code: 'FAR-INOTROP',
        service_name: 'Farmasi Khusus: Infus Inotropik, Heparin & Antiplatelet Ganda',
        service_category: 'farmasi',
        service_date: '2026-02-14',
        quantity: 14,
        unit: 'dosis',
        cost: 1420000,
      },
      {
        id: 'srv-4',
        service_code: 'LAB-ENZIM',
        service_name: 'Serial Enzim Jantung (Troponin I & CK-MB) + Elektrolit Darah',
        service_category: 'laboratorium',
        service_date: '2026-02-16',
        quantity: 4,
        unit: 'panel',
        cost: 760000,
      },
      {
        id: 'srv-5',
        service_code: 'VIS-SPJP',
        service_name: 'Visite Rutin Dokter Spesialis Jantung & Pembuluh Darah',
        service_category: 'visite_dokter',
        service_date: '2026-02-17',
        quantity: 7,
        unit: 'kali',
        cost: 640000,
      },
    ],
  },
  {
    id: 1025,
    episode_code: 'JKN-2026-092144',
    patient_pseudonym: 'Peserta Anonymized #92144 (Wanita, 63 th)',
    provider_id: 'PRV-JTG-004',
    provider_name: 'RSUD Dr. Moewardi Surakarta',
    provider_type: 'rsud_a',
    province_code: '33',
    province_name: 'Jawa Tengah',
    episode_type: 'rawat_inap',
    diagnosis_code: 'I63.9',
    diagnosis_group: 'Neurologi / Stroke',
    diagnosis_description: 'Cerebral Infarction / Stroke Iskemik Akut',
    length_of_stay: 8,
    service_utilization_count: 15,
    claim_cost: 9750000,
    risk_score: 88,
    risk_level: 'critical',
    readmission_risk: 41,
    episode_started_at: '2026-02-10',
    episode_ended_at: '2026-02-18',
    related_episodes_count: 2,
    notes: 'Hemiparesis dextra mendadak. Memerlukan observasi neurologi intensif dan terapi neuroprotektif.',
    services: [
      {
        id: 'srv-6',
        service_code: 'AKOM-NEURO',
        service_name: 'Akomodasi Perawatan Unit Stroke (8 Hari)',
        service_category: 'akomodasi',
        service_date: '2026-02-10',
        quantity: 8,
        unit: 'hari',
        cost: 3800000,
      },
      {
        id: 'srv-7',
        service_code: 'RAD-CT',
        service_name: 'Head CT-Scan Non-Kontras + Angiografi Serebral',
        service_category: 'tindakan_medis',
        service_date: '2026-02-10',
        quantity: 1,
        unit: 'tindakan',
        cost: 2100000,
      },
      {
        id: 'srv-8',
        service_code: 'FAR-TROMBO',
        service_name: 'Neuroprotektan, Manitol Infus & Antihipertensi Parenteral',
        service_category: 'farmasi',
        service_date: '2026-02-11',
        quantity: 12,
        unit: 'dosis',
        cost: 2150000,
      },
      {
        id: 'srv-9',
        service_code: 'REH-FISIO',
        service_name: 'Fisioterapi & Mobilisasi Dini Pasca Stroke',
        service_category: 'tindakan_medis',
        service_date: '2026-02-14',
        quantity: 5,
        unit: 'sesi',
        cost: 900000,
      },
      {
        id: 'srv-10',
        service_code: 'VIS-SPN',
        service_name: 'Visite Spesialis Saraf Konsultan Cerebrovascular',
        service_category: 'visite_dokter',
        service_date: '2026-02-12',
        quantity: 8,
        unit: 'kali',
        cost: 800000,
      },
    ],
  },
  {
    id: 1026,
    episode_code: 'JKN-2026-078310',
    patient_pseudonym: 'Peserta Anonymized #78310 (Pria, 51 th)',
    provider_id: 'PRV-DKI-012',
    provider_name: 'RSUD Tarakan',
    provider_type: 'rsud_b',
    province_code: '31',
    province_name: 'DKI Jakarta',
    episode_type: 'rawat_inap',
    diagnosis_code: 'E11.5',
    diagnosis_group: 'Endokrin / Diabetes',
    diagnosis_description: 'Diabetes Melitus Tipe 2 dengan Komplikasi Ulkus Kaki Diabetik',
    length_of_stay: 6,
    service_utilization_count: 9,
    claim_cost: 6800000,
    risk_score: 74,
    risk_level: 'high',
    readmission_risk: 29,
    episode_started_at: '2026-02-18',
    episode_ended_at: '2026-02-24',
    related_episodes_count: 4,
    notes: 'Debridement luka diabetik stage Wagner 2. Gula darah terkontrol sebelum pulang.',
    services: [
      {
        id: 'srv-11',
        service_code: 'AKOM-BEDAH',
        service_name: 'Akomodasi Ruang Rawat Bedah (6 Hari)',
        service_category: 'akomodasi',
        service_date: '2026-02-18',
        quantity: 6,
        unit: 'hari',
        cost: 2400000,
      },
      {
        id: 'srv-12',
        service_code: 'TIN-DEBRID',
        service_name: 'Tindakan Bedah Debridement & Perawatan Luka Modern',
        service_category: 'tindakan_medis',
        service_date: '2026-02-19',
        quantity: 2,
        unit: 'tindakan',
        cost: 2200000,
      },
      {
        id: 'srv-13',
        service_code: 'FAR-INSULIN',
        service_name: 'Regimen Insulin Analog & Antibiotik Broad Spectrum',
        service_category: 'farmasi',
        service_date: '2026-02-18',
        quantity: 10,
        unit: 'paket',
        cost: 1350000,
      },
      {
        id: 'srv-14',
        service_code: 'LAB-HBA1C',
        service_name: 'Laboratorium Glukosa Darah Serial, HbA1c & Kultur Luka',
        service_category: 'laboratorium',
        service_date: '2026-02-19',
        quantity: 3,
        unit: 'panel',
        cost: 450000,
      },
      {
        id: 'srv-15',
        service_code: 'VIS-SPB',
        service_name: 'Visite Spesialis Bedah Umum & Konsultasi Penyakit Dalam',
        service_category: 'visite_dokter',
        service_date: '2026-02-20',
        quantity: 6,
        unit: 'kali',
        cost: 400000,
      },
    ],
  },
  {
    id: 1027,
    episode_code: 'JKN-2026-110293',
    patient_pseudonym: 'Peserta Anonymized #110293 (Wanita, 48 th)',
    provider_id: 'PRV-DKI-002',
    provider_name: 'RSUP Fatmawati',
    provider_type: 'rsup',
    province_code: '31',
    province_name: 'DKI Jakarta',
    episode_type: 'rawat_inap',
    diagnosis_code: 'N18.5',
    diagnosis_group: 'Nefrologi / Ginjal',
    diagnosis_description: 'Penyakit Ginjal Kronik Stadium 5 on Hemodialisis Reguler',
    length_of_stay: 4,
    service_utilization_count: 8,
    claim_cost: 5250000,
    risk_score: 68,
    risk_level: 'high',
    readmission_risk: 32,
    episode_started_at: '2026-02-22',
    episode_ended_at: '2026-02-26',
    related_episodes_count: 8,
    notes: 'Klaim episode akut eksaserbasi overload cairan dan hiperkalemia pada pasien rutin HD.',
    services: [
      {
        id: 'srv-16',
        service_code: 'AKOM-IPD',
        service_name: 'Akomodasi Ruang Rawat Penyakit Dalam (4 Hari)',
        service_category: 'akomodasi',
        service_date: '2026-02-22',
        quantity: 4,
        unit: 'hari',
        cost: 1600000,
      },
      {
        id: 'srv-17',
        service_code: 'TIN-HD',
        service_name: 'Sesi Hemodialisis Cito & Koreksi Elektrolit Intensif',
        service_category: 'tindakan_medis',
        service_date: '2026-02-23',
        quantity: 2,
        unit: 'sesi',
        cost: 2100000,
      },
      {
        id: 'srv-18',
        service_code: 'FAR-EPO',
        service_name: 'Eritropoietin (EPO) & Obat Pengikat Fosfat',
        service_category: 'farmasi',
        service_date: '2026-02-24',
        quantity: 4,
        unit: 'ampul',
        cost: 950000,
      },
      {
        id: 'srv-19',
        service_code: 'LAB-KREATININ',
        service_name: 'Cek Ureum, Kreatinin, AGD & Elektrolit Serum',
        service_category: 'laboratorium',
        service_date: '2026-02-23',
        quantity: 2,
        unit: 'panel',
        cost: 320000,
      },
      {
        id: 'srv-20',
        service_code: 'VIS-SPPD',
        service_name: 'Visite Spesialis Penyakit Dalam Konsultan Ginjal Hipertensi',
        service_category: 'visite_dokter',
        service_date: '2026-02-24',
        quantity: 4,
        unit: 'kali',
        cost: 280000,
      },
    ],
  },
  {
    id: 1028,
    episode_code: 'JKN-2026-065120',
    patient_pseudonym: 'Peserta Anonymized #065120 (Pria, 69 th)',
    provider_id: 'PRV-JBR-005',
    provider_name: 'RSUP Dr. Hasan Sadikin',
    provider_type: 'rsup',
    province_code: '32',
    province_name: 'Jawa Barat',
    episode_type: 'rawat_inap',
    diagnosis_code: 'J44.1',
    diagnosis_group: 'Respirasi / Paru',
    diagnosis_description: 'PPOK dengan Eksaserbasi Akut & Pneumonia Bakterial',
    length_of_stay: 5,
    service_utilization_count: 10,
    claim_cost: 6100000,
    risk_score: 63,
    risk_level: 'high',
    readmission_risk: 26,
    episode_started_at: '2026-02-15',
    episode_ended_at: '2026-02-20',
    related_episodes_count: 1,
    notes: 'Pasien usia lanjut dengan sesak napas berat dan batuk produktif purulen.',
    services: [
      {
        id: 'srv-21',
        service_code: 'AKOM-RESP',
        service_name: 'Akomodasi Ruang Rawat Paru dengan Terapi Oksigen (5 Hari)',
        service_category: 'akomodasi',
        service_date: '2026-02-15',
        quantity: 5,
        unit: 'hari',
        cost: 2200000,
      },
      {
        id: 'srv-22',
        service_code: 'TIN-NEBUL',
        service_name: 'Nebulisasi Bronkodilator Terjadwal & Fisioterapi Dada',
        service_category: 'tindakan_medis',
        service_date: '2026-02-16',
        quantity: 10,
        unit: 'tindakan',
        cost: 1500000,
      },
      {
        id: 'srv-23',
        service_code: 'FAR-ANTIBIOTIK',
        service_name: 'Antibiotik Seftriakson, Azitromisin & Kortikosteroid Injeksi',
        service_category: 'farmasi',
        service_date: '2026-02-15',
        quantity: 8,
        unit: 'vial',
        cost: 1300000,
      },
      {
        id: 'srv-24',
        service_code: 'LAB-SPUTUM',
        service_name: 'Rontgen Thorax PA & Pemeriksaan Pewarnaan Gram Sputum',
        service_category: 'laboratorium',
        service_date: '2026-02-16',
        quantity: 2,
        unit: 'paket',
        cost: 650000,
      },
      {
        id: 'srv-25',
        service_code: 'VIS-SPP',
        service_name: 'Visite Spesialis Paru Konsultan Asma & PPOK',
        service_category: 'visite_dokter',
        service_date: '2026-02-17',
        quantity: 5,
        unit: 'kali',
        cost: 450000,
      },
    ],
  },
  {
    id: 1029,
    episode_code: 'JKN-2026-054901',
    patient_pseudonym: 'Peserta Anonymized #054901 (Wanita, 34 th)',
    provider_id: 'PRV-DIY-009',
    provider_name: 'RSUD Sleman',
    provider_type: 'rsud_b',
    province_code: '34',
    province_name: 'D.I. Yogyakarta',
    episode_type: 'rawat_inap',
    diagnosis_code: 'K35.8',
    diagnosis_group: 'Bedah Digestif',
    diagnosis_description: 'Apendisitis Akut Terperforasi dengan Peritonitis Lokal',
    length_of_stay: 5,
    service_utilization_count: 8,
    claim_cost: 5800000,
    risk_score: 58,
    risk_level: 'high',
    readmission_risk: 18,
    episode_started_at: '2026-02-05',
    episode_ended_at: '2026-02-10',
    related_episodes_count: 0,
    notes: 'Laparoskopi apendektomi darurat. Pemulihan saluran cerna berjalan baik.',
    services: [
      {
        id: 'srv-26',
        service_code: 'AKOM-BEDAH',
        service_name: 'Akomodasi Ruang Rawat Bedah (5 Hari)',
        service_category: 'akomodasi',
        service_date: '2026-02-05',
        quantity: 5,
        unit: 'hari',
        cost: 1850000,
      },
      {
        id: 'srv-27',
        service_code: 'TIN-APEND',
        service_name: 'Operasi Laparoskopi Apendektomi & Anestesi Umum',
        service_category: 'tindakan_medis',
        service_date: '2026-02-05',
        quantity: 1,
        unit: 'tindakan',
        cost: 2600000,
      },
      {
        id: 'srv-28',
        service_code: 'FAR-ANALGETIK',
        service_name: 'Antibiotik Perioperatif & Analgetik Infus Ketorolac',
        service_category: 'farmasi',
        service_date: '2026-02-06',
        quantity: 6,
        unit: 'dosis',
        cost: 750000,
      },
      {
        id: 'srv-29',
        service_code: 'LAB-DR',
        service_name: 'Darah Lengkap, Hemostasis & Elektrolit Pra-Bedah',
        service_category: 'laboratorium',
        service_date: '2026-02-05',
        quantity: 1,
        unit: 'panel',
        cost: 320000,
      },
      {
        id: 'srv-30',
        service_code: 'VIS-DOK',
        service_name: 'Visite Spesialis Bedah & Dokter Anestesi',
        service_category: 'visite_dokter',
        service_date: '2026-02-07',
        quantity: 5,
        unit: 'kali',
        cost: 280000,
      },
    ],
  },
  {
    id: 1030,
    episode_code: 'JKN-2026-031200',
    patient_pseudonym: 'Peserta Anonymized #031200 (Pria, 42 th)',
    provider_id: 'PRV-DIY-025',
    provider_name: 'Puskesmas Gondokusuman',
    provider_type: 'fktp_puskesmas',
    province_code: '34',
    province_name: 'D.I. Yogyakarta',
    episode_type: 'rawat_jalan',
    diagnosis_code: 'I10',
    diagnosis_group: 'Penyakit Tidak Menular (FKTP)',
    diagnosis_description: 'Hipertensi Primer / Esensial Grade 1 Terkontrol',
    length_of_stay: 0,
    service_utilization_count: 3,
    claim_cost: 350000,
    risk_score: 22,
    risk_level: 'low',
    readmission_risk: 5,
    episode_started_at: '2026-02-25',
    episode_ended_at: '2026-02-25',
    related_episodes_count: 5,
    notes: 'Kunjungan rutin Prolanis (Program Pengelolaan Penyakit Kronis). Edukasi gizi dan gaya hidup sehat.',
    services: [
      {
        id: 'srv-31',
        service_code: 'VIS-UMUM',
        service_name: 'Konsultasi & Pemeriksaan Dokter Umum FKTP',
        service_category: 'visite_dokter',
        service_date: '2026-02-25',
        quantity: 1,
        unit: 'kunjungan',
        cost: 100000,
      },
      {
        id: 'srv-32',
        service_code: 'FAR-AMLODIPIN',
        service_name: 'Obat Kronis 30 Hari: Amlodipin 10mg & Kandesartan 8mg',
        service_category: 'farmasi',
        service_date: '2026-02-25',
        quantity: 60,
        unit: 'tablet',
        cost: 180000,
      },
      {
        id: 'srv-33',
        service_code: 'LAB-SEDERHANA',
        service_name: 'Skrining Profil Lipid & Gula Darah Puasa POCT',
        service_category: 'laboratorium',
        service_date: '2026-02-25',
        quantity: 1,
        unit: 'skrining',
        cost: 70000,
      },
    ],
  },
];
